import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
  }

  class MyApp extends StatelessWidget {
    const MyApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  debugShowCheckedModeBanner: false,
                        title: 'Rawi',
                              theme: ThemeData(
                                      brightness: Brightness.dark,
                                              scaffoldBackgroundColor: const Color(0xFF0B0F14),
                                                      colorScheme: ColorScheme.fromSeed(
                                                                seedColor: const Color(0xFF4F8CFF),
                                                                          brightness: Brightness.dark,
                                                                                  ),
                                                                                          useMaterial3: true,
                                                                                                ),
                                                                                                      home: const RawiHomePage(),
                                                                                                          );
                                                                                                            }
                                                                                                            }

                                                                                                            class RawiHomePage extends StatelessWidget {
                                                                                                              const RawiHomePage({super.key});

                                                                                                                @override
                                                                                                                  Widget build(BuildContext context) {
                                                                                                                      return Scaffold(
                                                                                                                            appBar: AppBar(
                                                                                                                                    title: const Text(
                                                                                                                                              'راوي',
                                                                                                                                                        style: TextStyle(
                                                                                                                                                                    fontWeight: FontWeight.bold,
                                                                                                                                                                              ),
                                                                                                                                                                                      ),
                                                                                                                                                                                              centerTitle: true,
                                                                                                                                                                                                    ),
                                                                                                                                                                                                          body: SafeArea(
                                                                                                                                                                                                                  child: Padding(
                                                                                                                                                                                                                            padding: const EdgeInsets.all(20),
                                                                                                                                                                                                                                      child: Column(
                                                                                                                                                                                                                                                  children: [
                                                                                                                                                                                                                                                                const Spacer(),
                                                                                                                                                                                                                                                                              const Icon(
                                                                                                                                                                                                                                                                                              Icons.auto_awesome,
                                                                                                                                                                                                                                                                                                              size: 72,
                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                          const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                        const Text(
                                                                                                                                                                                                                                                                                                                                                                        'هلا بيك، أني راوي',
                                                                                                                                                                                                                                                                                                                                                                                        textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                        style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'مساعدك الرقمي',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 17,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const Spacer(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: double.infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: FilledButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPressed: () { Navigator.push(context, MaterialPageRoute(builder: (_) => const ChatPage())); },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: const Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: EdgeInsets.symmetric(vertical: 14),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'ابدأ المحادثة',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: TextStyle(fontSize: 17),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
class ChatPage extends StatelessWidget {
  const ChatPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('راوي'),
      ),
      body: const Center(
        child: Text(
          'هلا بيك، أني راوي\nشلون أگدر أساعدك؟',
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 22),
        ),
      ),
    );
  }
}
